.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. sequentia_qt test_sequentia_qt
clean: FORCE
	$(MAKE) -C .. sequentia_qt_clean test_sequentia_qt_clean
check: FORCE
	$(MAKE) -C .. test_sequentia_qt_check
sequentia-qt sequentia-qt.exe: FORCE
	 $(MAKE) -C .. sequentia_qt
apk: FORCE
	$(MAKE) -C .. sequentia_qt_apk
